variable "clid" {}
variable "clsecr" {}
variable "tid" {}
variable "subid" {}
variable "rg" {}
variable "location" {}
variable "nsg" {}
variable "vnet" {}
variable "dns_servers" {}
variable "address_space" {}
variable "snet1" {}
variable "snet2" {}
variable "address_prefixes1" {}
variable "address_prefixes2" {}
variable "pip" {}
variable "nic" {}
variable "ipconfig-name" {}
variable "vm" {}
variable "vm_size" {}
variable "systemname" {}
variable "adminuser" {}
variable "password" {}
